services:

  sqlpage:
    image: lovasoa/sqlpage
    volumes:
      - ./app:/var/www
      - ./sqlpage:/etc/sqlpage
    environment:
      - DATABASE_URL=postgres://pguser:changeit123@db/pguser
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8087:8080"

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changeit123
      POSTGRES_USER: pguser
      POSTGRES_DB: pguser
      TZ: America/Bogota
    healthcheck:
      test: pg_isready -U pguser -d pguser
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - "8999:8080"
